-- Paste this into Supabase SQL Editor (Dashboard > SQL Editor > New Query > Run)
-- It will skip cities that already exist

INSERT INTO cities (name, country, region, slug, timezone, is_active)
SELECT name, country, region, slug, timezone, true
FROM (VALUES
  ('Boston', 'USA', 'North America', 'boston', 'America/New_York'),
  ('Philadelphia', 'USA', 'North America', 'philadelphia', 'America/New_York'),
  ('Denver', 'USA', 'North America', 'denver', 'America/Denver'),
  ('Portland', 'USA', 'North America', 'portland', 'America/Los_Angeles'),
  ('San Diego', 'USA', 'North America', 'san-diego', 'America/Los_Angeles'),
  ('Honolulu', 'USA', 'North America', 'honolulu', 'Pacific/Honolulu'),
  ('Detroit', 'USA', 'North America', 'detroit', 'America/Detroit'),
  ('Minneapolis', 'USA', 'North America', 'minneapolis', 'America/Chicago'),
  ('Dallas', 'USA', 'North America', 'dallas', 'America/Chicago'),
  ('Houston', 'USA', 'North America', 'houston', 'America/Chicago'),
  ('Phoenix', 'USA', 'North America', 'phoenix', 'America/Phoenix'),
  ('Charlotte', 'USA', 'North America', 'charlotte', 'America/New_York'),
  ('Tampa', 'USA', 'North America', 'tampa', 'America/New_York'),
  ('Orlando', 'USA', 'North America', 'orlando', 'America/New_York'),
  ('Savannah', 'USA', 'North America', 'savannah', 'America/New_York'),
  ('Charleston', 'USA', 'North America', 'charleston', 'America/New_York'),
  ('Memphis', 'USA', 'North America', 'memphis', 'America/Chicago'),
  ('Pittsburgh', 'USA', 'North America', 'pittsburgh', 'America/New_York'),
  ('San Antonio', 'USA', 'North America', 'san-antonio', 'America/Chicago'),
  ('St. Louis', 'USA', 'North America', 'st-louis', 'America/Chicago'),
  ('Calgary', 'Canada', 'North America', 'calgary', 'America/Edmonton'),
  ('Ottawa', 'Canada', 'North America', 'ottawa', 'America/Toronto'),
  ('Quebec City', 'Canada', 'North America', 'quebec-city', 'America/Toronto'),
  ('Havana', 'Cuba', 'Caribbean', 'havana', 'America/Havana'),
  ('Kingston', 'Jamaica', 'Caribbean', 'kingston', 'America/Jamaica'),
  ('Nassau', 'Bahamas', 'Caribbean', 'nassau', 'America/Nassau'),
  ('Punta Cana', 'Dominican Republic', 'Caribbean', 'punta-cana', 'America/Santo_Domingo'),
  ('Bridgetown', 'Barbados', 'Caribbean', 'bridgetown', 'America/Barbados'),
  ('Madrid', 'Spain', 'Europe', 'madrid', 'Europe/Madrid'),
  ('Prague', 'Czech Republic', 'Europe', 'prague', 'Europe/Prague'),
  ('Vienna', 'Austria', 'Europe', 'vienna', 'Europe/Vienna'),
  ('Budapest', 'Hungary', 'Europe', 'budapest', 'Europe/Budapest'),
  ('Dublin', 'Ireland', 'Europe', 'dublin', 'Europe/Dublin'),
  ('Edinburgh', 'UK', 'Europe', 'edinburgh', 'Europe/London'),
  ('Copenhagen', 'Denmark', 'Europe', 'copenhagen', 'Europe/Copenhagen'),
  ('Stockholm', 'Sweden', 'Europe', 'stockholm', 'Europe/Stockholm'),
  ('Oslo', 'Norway', 'Europe', 'oslo', 'Europe/Oslo'),
  ('Helsinki', 'Finland', 'Europe', 'helsinki', 'Europe/Helsinki'),
  ('Warsaw', 'Poland', 'Europe', 'warsaw', 'Europe/Warsaw'),
  ('Krakow', 'Poland', 'Europe', 'krakow', 'Europe/Warsaw'),
  ('Athens', 'Greece', 'Europe', 'athens', 'Europe/Athens'),
  ('Santorini', 'Greece', 'Europe', 'santorini', 'Europe/Athens'),
  ('Istanbul', 'Turkey', 'Europe', 'istanbul', 'Europe/Istanbul'),
  ('Zurich', 'Switzerland', 'Europe', 'zurich', 'Europe/Zurich'),
  ('Milan', 'Italy', 'Europe', 'milan', 'Europe/Rome'),
  ('Florence', 'Italy', 'Europe', 'florence', 'Europe/Rome'),
  ('Venice', 'Italy', 'Europe', 'venice', 'Europe/Rome'),
  ('Munich', 'Germany', 'Europe', 'munich', 'Europe/Berlin'),
  ('Brussels', 'Belgium', 'Europe', 'brussels', 'Europe/Brussels'),
  ('Nice', 'France', 'Europe', 'nice', 'Europe/Paris'),
  ('Seville', 'Spain', 'Europe', 'seville', 'Europe/Madrid'),
  ('Hong Kong', 'China', 'Asia', 'hong-kong', 'Asia/Hong_Kong'),
  ('Shanghai', 'China', 'Asia', 'shanghai', 'Asia/Shanghai'),
  ('Beijing', 'China', 'Asia', 'beijing', 'Asia/Shanghai'),
  ('Taipei', 'Taiwan', 'Asia', 'taipei', 'Asia/Taipei'),
  ('Osaka', 'Japan', 'Asia', 'osaka', 'Asia/Tokyo'),
  ('Kyoto', 'Japan', 'Asia', 'kyoto', 'Asia/Tokyo'),
  ('Mumbai', 'India', 'Asia', 'mumbai', 'Asia/Kolkata'),
  ('Delhi', 'India', 'Asia', 'delhi', 'Asia/Kolkata'),
  ('Jaipur', 'India', 'Asia', 'jaipur', 'Asia/Kolkata'),
  ('Hanoi', 'Vietnam', 'Asia', 'hanoi', 'Asia/Ho_Chi_Minh'),
  ('Ho Chi Minh City', 'Vietnam', 'Asia', 'ho-chi-minh-city', 'Asia/Ho_Chi_Minh'),
  ('Kuala Lumpur', 'Malaysia', 'Asia', 'kuala-lumpur', 'Asia/Kuala_Lumpur'),
  ('Manila', 'Philippines', 'Asia', 'manila', 'Asia/Manila'),
  ('Colombo', 'Sri Lanka', 'Asia', 'colombo', 'Asia/Colombo'),
  ('Kathmandu', 'Nepal', 'Asia', 'kathmandu', 'Asia/Kathmandu'),
  ('Phnom Penh', 'Cambodia', 'Asia', 'phnom-penh', 'Asia/Phnom_Penh'),
  ('Chiang Mai', 'Thailand', 'Asia', 'chiang-mai', 'Asia/Bangkok'),
  ('Addis Ababa', 'Ethiopia', 'Africa', 'addis-ababa', 'Africa/Addis_Ababa'),
  ('Dar es Salaam', 'Tanzania', 'Africa', 'dar-es-salaam', 'Africa/Dar_es_Salaam'),
  ('Zanzibar', 'Tanzania', 'Africa', 'zanzibar', 'Africa/Dar_es_Salaam'),
  ('Dakar', 'Senegal', 'Africa', 'dakar', 'Africa/Dakar'),
  ('Casablanca', 'Morocco', 'Africa', 'casablanca', 'Africa/Casablanca'),
  ('Johannesburg', 'South Africa', 'Africa', 'johannesburg', 'Africa/Johannesburg'),
  ('Luanda', 'Angola', 'Africa', 'luanda', 'Africa/Luanda'),
  ('Abuja', 'Nigeria', 'Africa', 'abuja', 'Africa/Lagos'),
  ('Kigali', 'Rwanda', 'Africa', 'kigali', 'Africa/Kigali'),
  ('Kampala', 'Uganda', 'Africa', 'kampala', 'Africa/Kampala'),
  ('Bogota', 'Colombia', 'South America', 'bogota', 'America/Bogota'),
  ('Medellin', 'Colombia', 'South America', 'medellin', 'America/Bogota'),
  ('Cartagena', 'Colombia', 'South America', 'cartagena', 'America/Bogota'),
  ('Lima', 'Peru', 'South America', 'lima', 'America/Lima'),
  ('Cusco', 'Peru', 'South America', 'cusco', 'America/Lima'),
  ('Santiago', 'Chile', 'South America', 'santiago', 'America/Santiago'),
  ('Quito', 'Ecuador', 'South America', 'quito', 'America/Guayaquil'),
  ('Montevideo', 'Uruguay', 'South America', 'montevideo', 'America/Montevideo'),
  ('La Paz', 'Bolivia', 'South America', 'la-paz', 'America/La_Paz'),
  ('Sao Paulo', 'Brazil', 'South America', 'sao-paulo', 'America/Sao_Paulo'),
  ('Abu Dhabi', 'UAE', 'Middle East', 'abu-dhabi', 'Asia/Dubai'),
  ('Doha', 'Qatar', 'Middle East', 'doha', 'Asia/Qatar'),
  ('Riyadh', 'Saudi Arabia', 'Middle East', 'riyadh', 'Asia/Riyadh'),
  ('Amman', 'Jordan', 'Middle East', 'amman', 'Asia/Amman'),
  ('Beirut', 'Lebanon', 'Middle East', 'beirut', 'Asia/Beirut'),
  ('Muscat', 'Oman', 'Middle East', 'muscat', 'Asia/Muscat'),
  ('Auckland', 'New Zealand', 'Oceania', 'auckland', 'Pacific/Auckland'),
  ('Queenstown', 'New Zealand', 'Oceania', 'queenstown', 'Pacific/Auckland'),
  ('Perth', 'Australia', 'Oceania', 'perth', 'Australia/Perth'),
  ('Brisbane', 'Australia', 'Oceania', 'brisbane', 'Australia/Brisbane'),
  ('Fiji', 'Fiji', 'Oceania', 'fiji', 'Pacific/Fiji'),
  ('Panama City', 'Panama', 'Central America', 'panama-city', 'America/Panama'),
  ('San Jose', 'Costa Rica', 'Central America', 'san-jose-cr', 'America/Costa_Rica'),
  ('Guatemala City', 'Guatemala', 'Central America', 'guatemala-city', 'America/Guatemala'),
  ('Belize City', 'Belize', 'Central America', 'belize-city', 'America/Belize')
) AS new_cities(name, country, region, slug, timezone)
WHERE NOT EXISTS (
  SELECT 1 FROM cities WHERE cities.name = new_cities.name
);
